// <auto-generated />
using Business.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Business.Migrations
{
    [DbContext(typeof(BusinessContext))]
    partial class BusinessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Business.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("ShopType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("TypeCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Name = "Powells",
                            ShopType = "Store",
                            TypeCategory = "Books"
                        },
                        new
                        {
                            ShopId = 2,
                            Name = "Doe Donuts",
                            ShopType = "Restaurant",
                            TypeCategory = "Donuts"
                        },
                        new
                        {
                            ShopId = 3,
                            Name = "Mississippi Records",
                            ShopType = "Shop",
                            TypeCategory = "Music"
                        },
                        new
                        {
                            ShopId = 4,
                            Name = "Green Zebra",
                            ShopType = "Store",
                            TypeCategory = "Grocery"
                        },
                        new
                        {
                            ShopId = 5,
                            Name = "Babydoll Pizza",
                            ShopType = "Restaurant",
                            TypeCategory = "Pizza"
                        },
                        new
                        {
                            ShopId = 6,
                            Name = "New Seasons",
                            ShopType = "Store",
                            TypeCategory = "Grocery"
                        },
                        new
                        {
                            ShopId = 7,
                            Name = "JoJo's",
                            ShopType = "Restaurant",
                            TypeCategory = "Fried Chicken"
                        },
                        new
                        {
                            ShopId = 8,
                            Name = "People's Food Coop",
                            ShopType = "Store",
                            TypeCategory = "Grocery"
                        },
                        new
                        {
                            ShopId = 9,
                            Name = "Academy",
                            ShopType = "Theater",
                            TypeCategory = "Film"
                        },
                        new
                        {
                            ShopId = 10,
                            Name = "Arlene Schintzer",
                            ShopType = "Concert Hall",
                            TypeCategory = "Music"
                        },
                        new
                        {
                            ShopId = 11,
                            Name = "The Laurelhurst Theater",
                            ShopType = "Theater",
                            TypeCategory = "Film"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
